[package]
name = "advent_of_code_2015_day19"
version = "0.1.0"
edition = "2021"

[dependencies]
input_reader = { version = "0.1.0", path = "../../../../lib/input_reader" }
multimap = "0.10.0"

[lints]
workspace = true
