[package]
name = "advent_of_code_2015_day04"
version = "0.1.0"
edition = "2021"

[dependencies]
input_reader = { version = "0.1.0", path = "../../../../lib/input_reader" }
md-5 = "0.10.6"

[lints]
workspace = true
