[package]
name = "advent_of_code_2015_day09"
version = "0.1.0"
edition = "2021"

[dependencies]
input_reader = { version = "0.1.0", path = "../../../../lib/input_reader" }
itertools = "0.13.0"
petgraph = "0.6.5"

[lints]
workspace = true
